name: Backend

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  Build_GraphQL:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET v7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build
      run: dotnet build src/HotChocolateGraphQL.Backend -c Release
