name: Backend

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  Build_GraphQL:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET v9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: dotnet build src/HotChocolateGraphQL.Backend -c Release
