name: Backend

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  Build_GraphQL:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET v6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore src/HotChocolateGraphQL.Backend/

    - name: Build
      run: dotnet build src/HotChocolateGraphQL.Backend -c Release --no-restore
